export const technologies = [
  { name: "JavaScript", logo: "js", color: "#F7DF1E" },
  { name: "React", logo: "react", color: "#61DAFB" },
  { name: "Next", logo: "next", color: "#000000" },
  { name: "TypeScript", logo: "ts", color: "#3178C6" },
  { name: "Git", logo: "git", color: "#F05032" },
  { name: "React Hook Form", logo: "reactHookForm", color: "#EC5990" },
  { name: "Tanstack Query", logo: "tanstackQuery", color: "#FF4154" },
  { name: "React Router", logo: "reactRouter", color: "#CA4245" },
  { name: "HTML", logo: "html", color: "#E34F26" },
  { name: "CSS/SCSS", logo: "css", color: "#663399" },
  { name: "Bootstrap", logo: "bootstrap", color: "#7952B3" },
  { name: "Tailwind CSS", logo: "tailwind", color: "#06B6D4" },
  { name: "Redux", logo: "redux", color: "#764ABC" },
  { name: "Handlebars", logo: "handlebars", color: "#000000" },
  { name: "jQuery", logo: "jQuery", color: "#0769AD" },
  { name: "Vite", logo: "vite", color: "#646CFF" },
  // { name: "Vitest", logo: "vitest", color: "#6E9F18" },
  // { name: "Node.js", logo: "node", color: "#5FA04E" },
  // { name: "MongoDB", logo: "mongo", color: "#47A248" },
  // { name: "Mongoose", logo: "mongose", color: "#880000" },
  // { name: "Framer Motion", logo: "framer", color: "#0055FF" },
];
